[package]
name = "fepdf-font"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
bytes.workspace = true
thiserror.workspace = true
ttf-parser.workspace = true

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
