[package]
name = "ferruginous-sdk"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ferruginous-core.workspace = true
ferruginous-render.workspace = true
kurbo.workspace = true
thiserror.workspace = true
serde.workspace = true
bytes.workspace = true
ttf-parser.workspace = true
skrifa.workspace = true
roxmltree.workspace = true
image.workspace = true
tokio.workspace = true
pollster.workspace = true
flate2.workspace = true
lopdf.workspace = true
chrono.workspace = true
log.workspace = true
env_logger.workspace = true
hex.workspace = true
md5.workspace = true

[lints]
workspace = true
