[package]
name = "fepdf-model"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fepdf-macros.workspace = true
fepdf-font.workspace = true
fepdf-syntax.workspace = true
unicode-normalization.workspace = true
log.workspace = true
bytes.workspace = true
serde.workspace = true
thiserror.workspace = true
kurbo.workspace = true
flate2.workspace = true
image.workspace = true
roxmltree.workspace = true
moxcms.workspace = true
xmp-writer.workspace = true
rayon.workspace = true
id-arena.workspace = true
skrifa.workspace = true
read-fonts.workspace = true
ttf-parser.workspace = true
parking_lot.workspace = true
pdf-writer.workspace = true
zstd.workspace = true
aes.workspace = true
cbc.workspace = true
pbkdf2.workspace = true
sha2.workspace = true
hmac.workspace = true
rand.workspace = true
md5.workspace = true
hex.workspace = true
nom.workspace = true
x509-parser.workspace = true
reqwest.workspace = true
der.workspace = true
spki.workspace = true
rustls-native-certs.workspace = true
rsa.workspace = true
ecdsa.workspace = true
p256.workspace = true
signature.workspace = true
sha1.workspace = true

[features]
debug-tools = []

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
