//! The Annex D tables of ISO 32000-1:2008 the auditor names glyphs by.
//!
//! **Read out of `docs/specs/PDF32000_2008.pdf`, not written from memory**
//! ([ADR-0095](../../../docs/adr/0095-a-condition-citing-a-document-this-copy-lacks-is-not-implemented-from-memory.md)):
//! D.2's STD, MAC and WIN columns with the footnote marks taken off the names, the
//! duplicate codes its footnotes 5 and 6 add, D.5's Symbol names, and Table 115.

/// StandardEncoding's codes and names (ISO 32000-1:2008, D.2).
///
/// The 149 of them in the table's STD column, with the footnote marks taken off (`bullet3`
/// is `bullet`, `space6` is `space`).
pub const STANDARD_ENCODING: [(u8, &str); 149] = [
    (32, "space"),
    (33, "exclam"),
    (34, "quotedbl"),
    (35, "numbersign"),
    (36, "dollar"),
    (37, "percent"),
    (38, "ampersand"),
    (39, "quoteright"),
    (40, "parenleft"),
    (41, "parenright"),
    (42, "asterisk"),
    (43, "plus"),
    (44, "comma"),
    (45, "hyphen"),
    (46, "period"),
    (47, "slash"),
    (48, "zero"),
    (49, "one"),
    (50, "two"),
    (51, "three"),
    (52, "four"),
    (53, "five"),
    (54, "six"),
    (55, "seven"),
    (56, "eight"),
    (57, "nine"),
    (58, "colon"),
    (59, "semicolon"),
    (60, "less"),
    (61, "equal"),
    (62, "greater"),
    (63, "question"),
    (64, "at"),
    (65, "A"),
    (66, "B"),
    (67, "C"),
    (68, "D"),
    (69, "E"),
    (70, "F"),
    (71, "G"),
    (72, "H"),
    (73, "I"),
    (74, "J"),
    (75, "K"),
    (76, "L"),
    (77, "M"),
    (78, "N"),
    (79, "O"),
    (80, "P"),
    (81, "Q"),
    (82, "R"),
    (83, "S"),
    (84, "T"),
    (85, "U"),
    (86, "V"),
    (87, "W"),
    (88, "X"),
    (89, "Y"),
    (90, "Z"),
    (91, "bracketleft"),
    (92, "backslash"),
    (93, "bracketright"),
    (94, "asciicircum"),
    (95, "underscore"),
    (96, "quoteleft"),
    (97, "a"),
    (98, "b"),
    (99, "c"),
    (100, "d"),
    (101, "e"),
    (102, "f"),
    (103, "g"),
    (104, "h"),
    (105, "i"),
    (106, "j"),
    (107, "k"),
    (108, "l"),
    (109, "m"),
    (110, "n"),
    (111, "o"),
    (112, "p"),
    (113, "q"),
    (114, "r"),
    (115, "s"),
    (116, "t"),
    (117, "u"),
    (118, "v"),
    (119, "w"),
    (120, "x"),
    (121, "y"),
    (122, "z"),
    (123, "braceleft"),
    (124, "bar"),
    (125, "braceright"),
    (126, "asciitilde"),
    (161, "exclamdown"),
    (162, "cent"),
    (163, "sterling"),
    (164, "fraction"),
    (165, "yen"),
    (166, "florin"),
    (167, "section"),
    (168, "currency"),
    (169, "quotesingle"),
    (170, "quotedblleft"),
    (171, "guillemotleft"),
    (172, "guilsinglleft"),
    (173, "guilsinglright"),
    (174, "fi"),
    (175, "fl"),
    (177, "endash"),
    (178, "dagger"),
    (179, "daggerdbl"),
    (180, "periodcentered"),
    (182, "paragraph"),
    (183, "bullet"),
    (184, "quotesinglbase"),
    (185, "quotedblbase"),
    (186, "quotedblright"),
    (187, "guillemotright"),
    (188, "ellipsis"),
    (189, "perthousand"),
    (191, "questiondown"),
    (193, "grave"),
    (194, "acute"),
    (195, "circumflex"),
    (196, "tilde"),
    (197, "macron"),
    (198, "breve"),
    (199, "dotaccent"),
    (200, "dieresis"),
    (202, "ring"),
    (203, "cedilla"),
    (205, "hungarumlaut"),
    (206, "ogonek"),
    (207, "caron"),
    (208, "emdash"),
    (225, "AE"),
    (227, "ordfeminine"),
    (232, "Lslash"),
    (233, "Oslash"),
    (234, "OE"),
    (235, "ordmasculine"),
    (241, "ae"),
    (245, "dotlessi"),
    (248, "lslash"),
    (249, "oslash"),
    (250, "oe"),
    (251, "germandbls"),
];

/// MacRomanEncoding's codes and names (D.2).
///
/// The MAC column, and code 312 for `space`, which footnote 6 adds. Code 333 is
/// `currency` — footnote 1 keeps it so.
pub const MAC_ROMAN: [(u8, &str); 208] = [
    (32, "space"),
    (33, "exclam"),
    (34, "quotedbl"),
    (35, "numbersign"),
    (36, "dollar"),
    (37, "percent"),
    (38, "ampersand"),
    (39, "quotesingle"),
    (40, "parenleft"),
    (41, "parenright"),
    (42, "asterisk"),
    (43, "plus"),
    (44, "comma"),
    (45, "hyphen"),
    (46, "period"),
    (47, "slash"),
    (48, "zero"),
    (49, "one"),
    (50, "two"),
    (51, "three"),
    (52, "four"),
    (53, "five"),
    (54, "six"),
    (55, "seven"),
    (56, "eight"),
    (57, "nine"),
    (58, "colon"),
    (59, "semicolon"),
    (60, "less"),
    (61, "equal"),
    (62, "greater"),
    (63, "question"),
    (64, "at"),
    (65, "A"),
    (66, "B"),
    (67, "C"),
    (68, "D"),
    (69, "E"),
    (70, "F"),
    (71, "G"),
    (72, "H"),
    (73, "I"),
    (74, "J"),
    (75, "K"),
    (76, "L"),
    (77, "M"),
    (78, "N"),
    (79, "O"),
    (80, "P"),
    (81, "Q"),
    (82, "R"),
    (83, "S"),
    (84, "T"),
    (85, "U"),
    (86, "V"),
    (87, "W"),
    (88, "X"),
    (89, "Y"),
    (90, "Z"),
    (91, "bracketleft"),
    (92, "backslash"),
    (93, "bracketright"),
    (94, "asciicircum"),
    (95, "underscore"),
    (96, "grave"),
    (97, "a"),
    (98, "b"),
    (99, "c"),
    (100, "d"),
    (101, "e"),
    (102, "f"),
    (103, "g"),
    (104, "h"),
    (105, "i"),
    (106, "j"),
    (107, "k"),
    (108, "l"),
    (109, "m"),
    (110, "n"),
    (111, "o"),
    (112, "p"),
    (113, "q"),
    (114, "r"),
    (115, "s"),
    (116, "t"),
    (117, "u"),
    (118, "v"),
    (119, "w"),
    (120, "x"),
    (121, "y"),
    (122, "z"),
    (123, "braceleft"),
    (124, "bar"),
    (125, "braceright"),
    (126, "asciitilde"),
    (128, "Adieresis"),
    (129, "Aring"),
    (130, "Ccedilla"),
    (131, "Eacute"),
    (132, "Ntilde"),
    (133, "Odieresis"),
    (134, "Udieresis"),
    (135, "aacute"),
    (136, "agrave"),
    (137, "acircumflex"),
    (138, "adieresis"),
    (139, "atilde"),
    (140, "aring"),
    (141, "ccedilla"),
    (142, "eacute"),
    (143, "egrave"),
    (144, "ecircumflex"),
    (145, "edieresis"),
    (146, "iacute"),
    (147, "igrave"),
    (148, "icircumflex"),
    (149, "idieresis"),
    (150, "ntilde"),
    (151, "oacute"),
    (152, "ograve"),
    (153, "ocircumflex"),
    (154, "odieresis"),
    (155, "otilde"),
    (156, "uacute"),
    (157, "ugrave"),
    (158, "ucircumflex"),
    (159, "udieresis"),
    (160, "dagger"),
    (161, "degree"),
    (162, "cent"),
    (163, "sterling"),
    (164, "section"),
    (165, "bullet"),
    (166, "paragraph"),
    (167, "germandbls"),
    (168, "registered"),
    (169, "copyright"),
    (170, "trademark"),
    (171, "acute"),
    (172, "dieresis"),
    (174, "AE"),
    (175, "Oslash"),
    (177, "plusminus"),
    (180, "yen"),
    (181, "mu"),
    (187, "ordfeminine"),
    (188, "ordmasculine"),
    (190, "ae"),
    (191, "oslash"),
    (192, "questiondown"),
    (193, "exclamdown"),
    (194, "logicalnot"),
    (196, "florin"),
    (199, "guillemotleft"),
    (200, "guillemotright"),
    (201, "ellipsis"),
    (202, "space"),
    (203, "Agrave"),
    (204, "Atilde"),
    (205, "Otilde"),
    (206, "OE"),
    (207, "oe"),
    (208, "endash"),
    (209, "emdash"),
    (210, "quotedblleft"),
    (211, "quotedblright"),
    (212, "quoteleft"),
    (213, "quoteright"),
    (214, "divide"),
    (216, "ydieresis"),
    (217, "Ydieresis"),
    (218, "fraction"),
    (219, "currency"),
    (220, "guilsinglleft"),
    (221, "guilsinglright"),
    (222, "fi"),
    (223, "fl"),
    (224, "daggerdbl"),
    (225, "periodcentered"),
    (226, "quotesinglbase"),
    (227, "quotedblbase"),
    (228, "perthousand"),
    (229, "Acircumflex"),
    (230, "Ecircumflex"),
    (231, "Aacute"),
    (232, "Edieresis"),
    (233, "Egrave"),
    (234, "Iacute"),
    (235, "Icircumflex"),
    (236, "Idieresis"),
    (237, "Igrave"),
    (238, "Oacute"),
    (239, "Ocircumflex"),
    (241, "Ograve"),
    (242, "Uacute"),
    (243, "Ucircumflex"),
    (244, "Ugrave"),
    (245, "dotlessi"),
    (246, "circumflex"),
    (247, "tilde"),
    (248, "macron"),
    (249, "breve"),
    (250, "dotaccent"),
    (251, "ring"),
    (252, "cedilla"),
    (253, "hungarumlaut"),
    (254, "ogonek"),
    (255, "caron"),
];

/// WinAnsiEncoding's codes and names (D.2).
///
/// The WIN column, with 240 for `space` and 255 for `hyphen`, which footnotes 6 and 5 add.
/// The unused codes footnote 3 says map to `bullet` are not assigned, as it says.
pub const WIN_ANSI: [(u8, &str); 218] = [
    (32, "space"),
    (33, "exclam"),
    (34, "quotedbl"),
    (35, "numbersign"),
    (36, "dollar"),
    (37, "percent"),
    (38, "ampersand"),
    (39, "quotesingle"),
    (40, "parenleft"),
    (41, "parenright"),
    (42, "asterisk"),
    (43, "plus"),
    (44, "comma"),
    (45, "hyphen"),
    (46, "period"),
    (47, "slash"),
    (48, "zero"),
    (49, "one"),
    (50, "two"),
    (51, "three"),
    (52, "four"),
    (53, "five"),
    (54, "six"),
    (55, "seven"),
    (56, "eight"),
    (57, "nine"),
    (58, "colon"),
    (59, "semicolon"),
    (60, "less"),
    (61, "equal"),
    (62, "greater"),
    (63, "question"),
    (64, "at"),
    (65, "A"),
    (66, "B"),
    (67, "C"),
    (68, "D"),
    (69, "E"),
    (70, "F"),
    (71, "G"),
    (72, "H"),
    (73, "I"),
    (74, "J"),
    (75, "K"),
    (76, "L"),
    (77, "M"),
    (78, "N"),
    (79, "O"),
    (80, "P"),
    (81, "Q"),
    (82, "R"),
    (83, "S"),
    (84, "T"),
    (85, "U"),
    (86, "V"),
    (87, "W"),
    (88, "X"),
    (89, "Y"),
    (90, "Z"),
    (91, "bracketleft"),
    (92, "backslash"),
    (93, "bracketright"),
    (94, "asciicircum"),
    (95, "underscore"),
    (96, "grave"),
    (97, "a"),
    (98, "b"),
    (99, "c"),
    (100, "d"),
    (101, "e"),
    (102, "f"),
    (103, "g"),
    (104, "h"),
    (105, "i"),
    (106, "j"),
    (107, "k"),
    (108, "l"),
    (109, "m"),
    (110, "n"),
    (111, "o"),
    (112, "p"),
    (113, "q"),
    (114, "r"),
    (115, "s"),
    (116, "t"),
    (117, "u"),
    (118, "v"),
    (119, "w"),
    (120, "x"),
    (121, "y"),
    (122, "z"),
    (123, "braceleft"),
    (124, "bar"),
    (125, "braceright"),
    (126, "asciitilde"),
    (128, "Euro"),
    (130, "quotesinglbase"),
    (131, "florin"),
    (132, "quotedblbase"),
    (133, "ellipsis"),
    (134, "dagger"),
    (135, "daggerdbl"),
    (136, "circumflex"),
    (137, "perthousand"),
    (138, "Scaron"),
    (139, "guilsinglleft"),
    (140, "OE"),
    (142, "Zcaron"),
    (145, "quoteleft"),
    (146, "quoteright"),
    (147, "quotedblleft"),
    (148, "quotedblright"),
    (149, "bullet"),
    (150, "endash"),
    (151, "emdash"),
    (152, "tilde"),
    (153, "trademark"),
    (154, "scaron"),
    (155, "guilsinglright"),
    (156, "oe"),
    (158, "zcaron"),
    (159, "Ydieresis"),
    (160, "space"),
    (161, "exclamdown"),
    (162, "cent"),
    (163, "sterling"),
    (164, "currency"),
    (165, "yen"),
    (166, "brokenbar"),
    (167, "section"),
    (168, "dieresis"),
    (169, "copyright"),
    (170, "ordfeminine"),
    (171, "guillemotleft"),
    (172, "logicalnot"),
    (173, "hyphen"),
    (174, "registered"),
    (175, "macron"),
    (176, "degree"),
    (177, "plusminus"),
    (178, "twosuperior"),
    (179, "threesuperior"),
    (180, "acute"),
    (181, "mu"),
    (182, "paragraph"),
    (183, "periodcentered"),
    (184, "cedilla"),
    (185, "onesuperior"),
    (186, "ordmasculine"),
    (187, "guillemotright"),
    (188, "onequarter"),
    (189, "onehalf"),
    (190, "threequarters"),
    (191, "questiondown"),
    (192, "Agrave"),
    (193, "Aacute"),
    (194, "Acircumflex"),
    (195, "Atilde"),
    (196, "Adieresis"),
    (197, "Aring"),
    (198, "AE"),
    (199, "Ccedilla"),
    (200, "Egrave"),
    (201, "Eacute"),
    (202, "Ecircumflex"),
    (203, "Edieresis"),
    (204, "Igrave"),
    (205, "Iacute"),
    (206, "Icircumflex"),
    (207, "Idieresis"),
    (208, "Eth"),
    (209, "Ntilde"),
    (210, "Ograve"),
    (211, "Oacute"),
    (212, "Ocircumflex"),
    (213, "Otilde"),
    (214, "Odieresis"),
    (215, "multiply"),
    (216, "Oslash"),
    (217, "Ugrave"),
    (218, "Uacute"),
    (219, "Ucircumflex"),
    (220, "Udieresis"),
    (221, "Yacute"),
    (222, "Thorn"),
    (223, "germandbls"),
    (224, "agrave"),
    (225, "aacute"),
    (226, "acircumflex"),
    (227, "atilde"),
    (228, "adieresis"),
    (229, "aring"),
    (230, "ae"),
    (231, "ccedilla"),
    (232, "egrave"),
    (233, "eacute"),
    (234, "ecircumflex"),
    (235, "edieresis"),
    (236, "igrave"),
    (237, "iacute"),
    (238, "icircumflex"),
    (239, "idieresis"),
    (240, "eth"),
    (241, "ntilde"),
    (242, "ograve"),
    (243, "oacute"),
    (244, "ocircumflex"),
    (245, "otilde"),
    (246, "odieresis"),
    (247, "divide"),
    (248, "oslash"),
    (249, "ugrave"),
    (250, "uacute"),
    (251, "ucircumflex"),
    (252, "udieresis"),
    (253, "yacute"),
    (254, "thorn"),
    (255, "ydieresis"),
];

/// The standard Roman encoding of Mac OS where it differs from MacRomanEncoding (9.6.6.4,
/// Table 115): fifteen additions, and `Euro` in place of `currency` at 333.
pub const MAC_OS_ROMAN_DIFFERENCES: [(&str, u8); 16] = [
    ("notequal", 173),
    ("infinity", 176),
    ("lessequal", 178),
    ("greaterequal", 179),
    ("partialdiff", 182),
    ("summation", 183),
    ("product", 184),
    ("pi", 185),
    ("integral", 186),
    ("Omega", 189),
    ("radical", 195),
    ("approxequal", 197),
    ("Delta", 198),
    ("lozenge", 215),
    ("Euro", 219),
    ("apple", 240),
];

/// The Mac OS standard Roman code for a glyph name (9.6.6.4): Table 115's, then
/// MacRomanEncoding's — less `currency`, whose code is `Euro`'s there.
#[must_use]
pub fn mac_os_roman_code(name: &str) -> Option<u8> {
    if let Some((_, code)) = MAC_OS_ROMAN_DIFFERENCES.iter().find(|(n, _)| *n == name) {
        return Some(*code);
    }
    if name == "currency" {
        return None;
    }
    MAC_ROMAN.iter().find(|(_, n)| *n == name).map(|(code, _)| *code)
}

/// ISO 32000-1:2008, Annex D.5: the Symbol font's named characters, which 31-027 accepts
/// beside Adobe's list.
pub const SYMBOL_NAMES: [&str; 189] = [
    "Alpha",
    "Beta",
    "Chi",
    "Delta",
    "Epsilon",
    "Eta",
    "Euro",
    "Gamma",
    "Ifraktur",
    "Iota",
    "Kappa",
    "Lambda",
    "Mu",
    "Nu",
    "Omega",
    "Omicron",
    "Phi",
    "Pi",
    "Psi",
    "Rfraktur",
    "Rho",
    "Sigma",
    "Tau",
    "Theta",
    "Upsilon",
    "Upsilon1",
    "Xi",
    "Zeta",
    "aleph",
    "alpha",
    "ampersand",
    "angle",
    "angleleft",
    "angleright",
    "approxequal",
    "arrowboth",
    "arrowdblboth",
    "arrowdbldown",
    "arrowdblleft",
    "arrowdblright",
    "arrowdblup",
    "arrowdown",
    "arrowhorizex",
    "arrowleft",
    "arrowright",
    "arrowup",
    "arrowvertex",
    "asteriskmath",
    "bar",
    "beta",
    "braceex",
    "braceleft",
    "braceleftbt",
    "braceleftmid",
    "bracelefttp",
    "braceright",
    "bracerightbt",
    "bracerightmid",
    "bracerighttp",
    "bracketleft",
    "bracketleftbt",
    "bracketleftex",
    "bracketlefttp",
    "bracketright",
    "bracketrightbt",
    "bracketrightex",
    "bracketrighttp",
    "bullet",
    "carriagereturn",
    "chi",
    "circlemultiply",
    "circleplus",
    "club",
    "colon",
    "comma",
    "congruent",
    "copyrightsans",
    "copyrightserif",
    "degree",
    "delta",
    "diamond",
    "divide",
    "dotmath",
    "eight",
    "element",
    "ellipsis",
    "emptyset",
    "epsilon",
    "equal",
    "equivalence",
    "eta",
    "exclam",
    "existential",
    "five",
    "florin",
    "four",
    "fraction",
    "gamma",
    "gradient",
    "greater",
    "greaterequal",
    "heart",
    "infinity",
    "integral",
    "integralbt",
    "integralex",
    "integraltp",
    "intersection",
    "iota",
    "kappa",
    "lambda",
    "less",
    "lessequal",
    "logicaland",
    "logicalnot",
    "logicalor",
    "lozenge",
    "minus",
    "minute",
    "mu",
    "multiply",
    "nine",
    "notelement",
    "notequal",
    "notsubset",
    "nu",
    "numbersign",
    "omega",
    "omega1",
    "omicron",
    "one",
    "parenleft",
    "parenleftbt",
    "parenleftex",
    "parenlefttp",
    "parenright",
    "parenrightbt",
    "parenrightex",
    "parenrighttp",
    "partialdiff",
    "percent",
    "period",
    "perpendicular",
    "phi",
    "phi1",
    "pi",
    "plus",
    "plusminus",
    "product",
    "propersubset",
    "propersuperset",
    "proportional",
    "psi",
    "question",
    "radical",
    "radicalex",
    "reflexsubset",
    "reflexsuperset",
    "registersans",
    "registerserif",
    "rho",
    "second",
    "semicolon",
    "seven",
    "sigma",
    "sigma1",
    "similar",
    "six",
    "slash",
    "space",
    "spade",
    "suchthat",
    "summation",
    "tau",
    "therefore",
    "theta",
    "theta1",
    "three",
    "trademarksans",
    "trademarkserif",
    "two",
    "underscore",
    "union",
    "universal",
    "upsilon",
    "weierstrass",
    "xi",
    "zero",
    "zeta",
];

/// The tables against what D.2 says of them besides their rows.
#[cfg(test)]
mod the_tables {
    use super::{MAC_ROMAN, STANDARD_ENCODING, WIN_ANSI, mac_os_roman_code};

    /// Footnotes 5 and 6: the duplicate codes the rows do not carry.
    #[test]
    fn the_footnotes_duplicates_are_there() {
        assert!(WIN_ANSI.contains(&(0o240, "space")) && WIN_ANSI.contains(&(0o255, "hyphen")));
        assert!(MAC_ROMAN.contains(&(0o312, "space")));
    }

    /// Footnote 1 keeps `currency` at 333 in MacRomanEncoding, and Table 115 puts `Euro`
    /// there on Mac OS.
    #[test]
    fn mac_os_roman_is_mac_roman_with_table_115() {
        assert!(MAC_ROMAN.contains(&(0o333, "currency")));
        assert_eq!(mac_os_roman_code("Euro"), Some(219));
        assert_eq!(mac_os_roman_code("currency"), None);
        assert_eq!(mac_os_roman_code("notequal"), Some(173));
        assert_eq!(mac_os_roman_code("A"), Some(0x41));
    }

    /// Every code appears once in each table.
    #[test]
    fn no_code_is_named_twice() {
        for table in [&STANDARD_ENCODING[..], &MAC_ROMAN[..], &WIN_ANSI[..]] {
            let codes: std::collections::BTreeSet<u8> = table.iter().map(|(c, _)| *c).collect();
            assert_eq!(codes.len(), table.len());
        }
    }
}
